CREATE DATABASE [programmingchallenge]

USE [programmingchallenge]

CREATE TABLE Title (
	ID int NOT NULL,
	TITLETYPE varchar(100),
	PRIMARYTITLE varchar(1000),
	ORIGINALTITLE varchar(1000),
	ISADULT bit,
	STARTYEAR int,
	ENDYEAR int,
	RUNTIMEMINUTES int,
	PRIMARY KEY (ID)
)

CREATE TABLE People (
	ID int NOT NULL,
	PRIMARYNAME varchar(1000),
	BIRTHYEAR int,
	DEATHYEAR int,
	PRIMARY KEY (ID)
)

CREATE TABLE TitleGenres (
	ID int IDENTITY(1,1) NOT NULL,
	GENRENAME varchar(200) NOT NULL,
	PRIMARY KEY (ID)
	)

CREATE TABLE TitleGenres_Title (
	TITLEID int NOT NULL,
	GENREID int NOT NULL,
	FOREIGN KEY (TITLEID) REFERENCES Title(ID),
	FOREIGN KEY (GENREID) REFERENCES TitleGenres(ID)
)

CREATE TABLE Profession (
	ID int IDENTITY(1,1) NOT NULL,
	PROFESSIONNAME varchar(200) NOT NULL,
	PRIMARY KEY (ID)
)

CREATE TABLE Profession_People (
	PROFESSIONID int NOT NULL,
	PEOPLEID int NOT NULL,
	FOREIGN KEY (PROFESSIONID) REFERENCES Profession(ID),
	FOREIGN KEY (PEOPLEID) REFERENCES People(ID)
	)

CREATE TABLE TitleRatings (
	TITLEID int NOT NULL,
	RATING numeric(4,2),
	NUMVOTES int NOT NULL,
	FOREIGN KEY (TITLEID) REFERENCES Title(ID)
)

CREATE TABLE Title_People (
	TITLEID int NOT NULL,
	PEOPLEID int NOT NULL,
	FOREIGN KEY (TITLEID) REFERENCES Title(ID),
	FOREIGN KEY (PEOPLEID) REFERENCES People(ID)
	)
	

  CREATE INDEX INDEX_RATING
ON TitleRatings(RATING);

CREATE INDEX INDEX_TITLEID_GENRE
ON TITLEGENRES_TITLE(TITLEID);

CREATE INDEX INDEX_PEOPLEID_PROFESSION
ON PROFESSION_PEOPLE(PEOPLEID);

